name: Review package
on:
  push:
    branches: ['dev']
  pull_request:
    types:
      - opened

jobs:
  test:
    name: 'Node.js v${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 14

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node }}'
      - uses: actions/checkout@v2
      - name: 'Cache node_modules'
        uses: actions/cache@v2

        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v${{ matrix.node }}-
      - name: Install Dependencies
        run: |
          npm audit fix
          npm install

      - name: run code coverage
        env:
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: npm run coverage

      - name: report code coverage
        run: npm run report-coverage

      - name: upload coverage report to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
